#!/home/ryu/.rvm/rubies/ruby-2.5.1/bin/ruby
require "sdl2"
require "yaml"
require "./akane_sound/module.util.rb"

class Akane
  @@window = nil
  @@renderer = nil
  @@pref_dir = nil
  @@screen = nil
  @@status = nil
  @@config = Hash.new
  @@save_data = Hash.new
  @@alert_flag = false
  @@inp = nil
  @@debug_flag = false
  def initialize
    SDL2.init(SDL2::INIT_TIMER|SDL2::INIT_AUDIO|SDL2::INIT_VIDEO|
              SDL2::INIT_EVENTS)
    SDL2::TTF.init

    @@pref_dir = SDL2.preference_path("sxp", "akane_sound")
    Setup::prepare_config
    Setup::prepare_binary_data('akane_bg.png')
    Setup::prepare_binary_data('KosugiMaru-Regular.ttf')
    
    @@window = SDL2::Window.create("akane_sound", SDL2::Window::POS_CENTERED,
                                   SDL2::Window::POS_CENTERED,
                                   @@config[:window_w], @@config[:window_h], 0)

    @@renderer = @@window.create_renderer(-1, 0)
    @@screen = SDL2::Rect[0, 0, @@config[:window_w], @@config[:window_h]]

  end

  def run(argv)
    if ARGV[0] == "debug"
      @@debug_flag = true
      File.delete(File.open(@@pref_dir+'config.yaml'))
    end
    font = SDL2::TTF.open(@@config[:font], 20)

    bg = Background.new(@@config[:bg_img])
    @@inp = Input.new
    @@sec_status = SectionStatus.new(0, 400, 640, 80, @@config[:view_bottom_bg_color])
    sec_dir = SectionDir.new(0, 0, 320, 400, @@config[:view_left_bg_color])
    sec_pl = SectionPlaylist.new(320, 0, 320, 400, @@config[:view_right_bg_color])
    loop do
      while event = SDL2::Event.poll
        @@inp.handle_event(event)
      end
      #update
      bg.update
      #draw
      @@renderer.viewport = nil
      bg.draw
      sec_dir.draw
      sec_pl.draw
      @@sec_status.draw
      @@renderer.present
      if @@inp.quit >= 1
        exit
      end
    end
  end


  def prepare_save_data
  end
end

require "./akane_sound/class.setup.rb"
require "./akane_sound/class.background.rb"
require "./akane_sound/class.input.rb"
require "./akane_sound/class.view_base.rb"
require "./akane_sound/class.upper_section_base.rb"
require "./akane_sound/class.section_dir.rb"
require "./akane_sound/class.section_playlist.rb"
require "./akane_sound/class.section_status.rb"

Akane.new.run(ARGV)
