---
:window_w: 640
:window_h: 480
:sleep_timer: 0 # seconds without input until player goes into sleep. 0 diables the feature
:bg_img: 'FILE_PATH_BG'
:font: 'FILE_PATH_FONT'
:font_big: 'FILE_PATH_FONT_BIG'
:font_size: 14
:line_height_mod: 1.5
:root_dir: 'FILE_PATH_ROOT'
:bg_type: 'repeat' # 'none', 'center', 'tile', 'scale', 'stretch', 'fit'
:bg_color:
    :red: 0
    :green: 0
    :blue: 20
    :alpha: 155
:view_left_bg_color:
    :red: 200
    :green: 0
    :blue: 20
    :alpha: 80
:view_right_bg_color:
    :red: 0
    :green: 200
    :blue: 20
    :alpha: 80
:view_bottom_bg_color:
    :red: 0
    :green: 0
    :blue: 20
    :alpha: 255
:fg_color:
    :red: 255
    :green: 255
    :blue: 255
    :alpha: 255
:text_color:
    :red: 255
    :green: 255
    :blue: 255
    :alpha: 255
:volume_bar_color:
    :red: 0
    :green: 255
    :blue: 55
    :alpha: 0
:prog_bar_color:
    :red: 0
    :green: 155
    :blue: 155
    :alpha: 0
:select_bg_color:
    :red: 255
    :green: 255
    :blue: 255
    :alpha: 0


